
SELECT P.BIRTH_DATE 생년월일,P.PLAYER_NAME 선수
FROM PLAYER P
WHERE P.BIRTH_DATE IS NOT NULL AND ROWNUM BETWEEN 1 AND 5
ORDER BY P.BIRTH_DATE DESC;


SELECT P.BIRTH_DATE 생년월일,P.PLAYER_NAME 선수
FROM (SELECT BIRTH_DATE,PLAYER_NAME
      FROM PLAYER
      WHERE BIRTH_DATE IS NOT NULL
      ORDER BY BIRTH_DATE DESC) P
WHERE ROWNUM BETWEEN 1 AND 5;




SELECT rnum no, BIRTH_DATE 생년월일,PLAYER_NAME 선수 
FROM (SELECT BIRTH_DATE ,PLAYER_NAME , ROWNUM rnum 
            FROM (SELECT BIRTH_DATE ,PLAYER_NAME
                  FROM PLAYER
                  WHERE BIRTH_DATE IS NOT NULL
                  ORDER BY BIRTH_DATE DESC))
WHERE rnum BETWEEN 6 AND 10;

select * from player;

--1.현재목록에서 ROWNUM을 추가한다.
SELECT ROWNUM no,CUSTOMER_ID,CUSTOMER_NAME,PASSWORD,SSN,PHONE,CITY,ADDRESS,POSTALCODE
FROM CUSTOMERS C

;
--2.ROWNUM 역순으로 정렬한다
SELECT ROWNUM no,C.*
FROM CUSTOMERS C
ORDER BY no desc;

--3.페이지사이즈만큼만(5) 출력한다.
SELECT d.*
FROM (SELECT ROWNUM no, C.*
      FROM CUSTOMERS C
      ORDER BY no desc) d
where no between 27 and 31;


SELECT D1.*
FROM (SELECT ROWNUM NO1,D.*
      FROM (SELECT ROWNUM NO, C.*
            FROM CUSTOMERS C
            ORDER BY no desc) D)D1
WHERE NO1 BETWEEN 1 AND 5;       


SELECT COUNT(*) COUNT
FROM CUSTOMERS;