SELECT * FROM TAB;
SELECT * FROM EMPLOYEES;
ALTER TABLE CUSTOMERS RENAME COLUMN PASSWORD TO CUSTOMER_NAME;
ALTER TABLE CUSTOMERS RENAME COLUMN CONTACT_NAME TO PASSWORD;
ALTER TABLE EMPLOYEES ADD NOTES VARCHAR2(20);PASSWORD;

UPDATE CUSTOMERS
SET PASSWORD = '1',
 PHONE = '2',
 CITY = '3',
 ADDRESS = '4',
 POSTALCODE ='5'
 WHERE CUSTOMERID LIKE ?
 ;