CREATE TABLE IMAGE(
    IMG_SEQ NUMBER PRIMARY KEY,
    IMG_NAME VARCHAR2(50),
    IMG_EXTENTION VARCHAR2(50),
    OWNER VARCHAR2(50)
    
);
SELECT *
FROM IMAGE;
SELECT IMG_SEQ
FROM (SELECT ROWNUM RN,IMG_SEQ,IMG_NAME,IMG_EXTENTION
      FROM IMAGE 
      ORDER BY RN DESC)
WHERE RN LIKE 1;
 INSERT INTO IMAGE(IMG_SEQ,IMG_NAME,IMG_EXTENTION,OWNER)
 VALUES(IMG_SEQ.NEXTVAL,'default_photo','jpg','°ü¸®ÀÚ');
 
 SELECT MAX(IMG_SEQ) last,(SELECT IMG_NAME
                           FROM IMAGE
                           WHERE IMG_SEQ LIKE MAX(IMG_SEQ))
 FROM IMAGE
 ;
  SELECT MAX(IMG_SEQ) LAST,IMG_NAME
 FROM IMAGE
 GROUP BY IMG_NAME
;




SELECT IMG_SEQ LAST ,IMG_NAME
FROM IMAGE
WHERE IMG_SEQ LIKE ((SELECT MAX(IMG_SEQ)
                     FROM IMAGE))
;
 
 SELECT *
 FROM IMAGE
 WHERE IMG_SEQ LIKE 1000;
      
       
SELECT * FROM CUSTOMERS;



 SELECT IMG_SEQ   
 FROM IMAGE  
 WHERE IMG_SEQ LIKE ((SELECT MAX(IMG_SEQ) d 
                    FROM IMAGE));